### PR TITLE
Updates for Visual Studio 2019

### PR DESCRIPTION
**Pull request by gsf600y**
The [build instructions](http://www.softdevlabs.com/hercules-vs2015-build.html) for SDL Hyperion document Visual Studio Community 2017, which is no longer easily (that I could find) available for download from Microsoft.  Visual Studio Community 2019 however is readily available.

These updates allow building the code using Visual Studio 2019.

First time using GitHub, so hoping what I've done is correct.

### CODE REVIEW

**Comment by Vf58** [comment]
Hello,


I use Visual Studio 2019 and it's working fine.

I would just mention that the following documentation in http://www.softdevlabs.com/hercules-vs2015-build.html is obsolete 

"Visual Studio's Property Sheets live in the C:\Users\<username>\AppData\Local\Microsoft\MSBuild\v4.0 directory. The two Property Sheets that we need to modify are the "Microsoft.Cpp.Win32.user.props" and "Microsoft.Cpp.x64.user.props" sheets. Edit both files in Notepad and replace line 6 ("<PropertyGroup />") with the following three lines:

        <PropertyGroup>
          <IncludePath>$(VC_IncludePath);$(WindowsSDK_IncludePath);$(INCLUDE);</IncludePath>
        </PropertyGroup>

As you can see all we are doing is appending the "INCLUDE" directory to the end of Visual Studio's default INCLUDE directories. This allows Hercules to find the all important "win32.mak" file. "

The include Path can be directly added in Visual Studio 2019.
1) Choose your kind of generation (for me: release & X64)
2) -> Properties ->Folder VC++ -> Include Folder , (Hope it is 'folder' I use the french version 'répertoire')
add your path (C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include) add the end.

Perform the above operation for all of your kind of generation...

Is it may be explained in another issue but I do not find it, my apologizes if it is the case.

Hoping you agree with the above.


Philippe

**Comment by Fish-Git** [comment]
> I would just mention that the following documentation in http://www.softdevlabs.com/hercules-vs2015-build.html is obsolete

I disagree.

> The include Path can be directly added in Visual Studio 2019.
> 
> 1. Choose your kind of generation (for me: release & X64)
> 2. -> Properties ->Folder VC++ -> Include Folder , (Hope it is 'folder' I use the french version 'répertoire')
>    add your path (C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include) add the end.
> 
> Perform the above operation for all of your kind of generation...

I know that.

But you're missing the point.

The point is, Visual Studio should not be arbitrarily ignoring the directories defined in your INCLUDE environment variable (which it is doing without the change).

A person's INCLUDE environment variable might have many directories defined that the compiler should be searching. Without the changes described on my web page, the compiler would never be searching those directories. This is a serious bug/oversight in Visual Studio IMHO (i.e. bad design).

Unfortunately the Visual Studio team at Microsoft thinks just like you. They seem to think that you shouldn't be using environment variables. That you should instead always use their GUI and  just manually add each and every extra include directory into Visual Studio's user interface each time you create a new project.

But if your INCLUDE environment variable has 10 different search directories defined, then you would need to manually add those 10 directories to Visual Studio each and every time you create a new project!

What's worse is, what if you want to _change_ one or more of those directories? (e.g. change the name of one of the existing directories or add a new directory, or delete an existing directory, or change the order in which they're searched?) What then?

You would then need to open each and every existing visual studio project and change them all! What if you have 100 projects? Are you going to manually change each one simply because you want to add a new search directory?

That's nuts!

Instead, Visual Studio should be fixed to honor a user's INCLUDE environment variable. That's what my web page does: it essentially forces Visual Studio to behave correctly by causing it to always search all directories defined in your INCLUDE environment variable. That way all you have to do is update your INCLUDE environment variable and you're done! All 100 of your existing projects will immediately begin searching the new directory. That's the way it _supposed_ to work.

> Hoping you agree with the above.

I'm sorry, but no, I cannot agree.

My web page is correct, and most certainly is _not_ obsolete.

**Comment by Vf58** [comment]
Hello Fish,

in fact the thing that seems to be obsolete is the path 'C:\Users\<username>\AppData\Local\Microsoft\MSBuild\v4.0 ' which doesn't exist anymore, is somewhere else or should I had to create it?. For somebody like me who never use Visual Studio but for Hercules I had to perform some research.

For the way it is working, I totally agree with you. It would be possible to specify a global path for all projects and local paths which are projet related.
And I prove it... I send you yesterday a Email with 'nice to have functionnalities' for HercGUI because as I have many machines, I organized my Hercules folders in such way.
A global folder with 'Configuration files', Dasd, Printer, Sricpts  Sub_Folders and many locals folders (with also 'Configuration files', Dasd, Tape, Srcipts sub-folders) with specifics configuration.
The global are the one specified in HercGui directories configurations and Locals are defined by the way of DEFSYM... The only thing I don't know is how to change by configuration or by script command the path where to find the scripts. And also for scripts It could be nice to have a king of concatanation $(local);$(global).
I'm happy to see we are on the same way  ;-)


My apologozises for the 'obsolete' keyword,


Philippe

**Comment by wrljet** [comment]
This page tries to explain the change in property sheet locations for VS2019 and why MSFT did it.

https://docs.microsoft.com/en-us/cpp/build/create-reusable-property-configurations?view=vs-2019

On one of my systems, as an example, it moved from VS2017:
    `C:\Users\bill\AppData\Local\Microsoft\MSBuild\v4.0\`
to on VS2019:
    `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\`

Bill

**Comment by Vf58** [comment]
Hello Bill

Thank you for this interesting link

Philippe

**Comment by Fish-Git** [comment]
Vf58 wrote:

> In fact, the thing that seems to be obsolete is the path:
> 
> ```
>    C:\Users\<username>\AppData\Local\Microsoft\MSBuild\v4.0
> ```
> 
> which doesn't exist anymore, is somewhere else or should I had to create it? For somebody like me who never use Visual Studio but for Hercules I had to perform some research.

Oh! Okay. I understand now.

I originally misunderstood your "obsolete" reference. I thought you were saying my entire web page was obsolete. But what you actually meant was the _**PATH**_ was obsolete for _**VS2019**_.

I understand now. Thank you. My apologies for the confusion (misunderstanding).

&nbsp;
wrljet wrote:

> On one of my systems, as an example, it moved from VS2017:
> 
> ```
>    C:\Users\bill\AppData\Local\Microsoft\MSBuild\v4.0\
> ```
> 
> to on VS2019:
> 
> ```
>    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\
> ```

Thank you, Bill.

When I find the time (HA!) I will try to update the web page with information for VS2019.

Thank you both.

**Comment by wrljet** [comment]
As an aside, IMHO, there's little reason to move from VS2017 to VS2019.
It's just bigger and more bloated and more stupid stuff added.

Bill

**Comment by Fish-Git** [comment]
> As an aside, IMHO, there's little reason to move from VS2017 to VS2019.
> It's just bigger and more bloated and more stupid stuff added.

Why do you think I'm still using _**VS2008!**_ &nbsp; `;-)`

_(my own VS2017 install only exists in a VMware virtual machine used exclusively for Hercules testing only. My primary host system however -- which is what I use for ALL of my software development, Hercules included -- still only has VS2008!)_

**Comment by Vf58** [comment]
No problem Fish, my sentence wasn't clear.

Philippe

**Pull request merged**
