### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by JamesWekel**
Fish,

A couple of minor updates:

1. remove a build GCC uninitialized warning message in dfp.c.
2. Fix TRE-02-performance.asm that has 10 missing instruction tests and do some cosmetic cleanup.

Just had to do one more thing...

Jim

### CODE REVIEW

**Comment by Fish-Git** [comment]
> 1. remove a build GCC uninitialized warning message in dfp.c.

I'll take care of that myself. Thanks.

> 2. Fix TRE-02-performance.asm that has 10 missing instruction tests and do some cosmetic cleanup.

Too late! &nbsp;`:)`

I already noticed the same problem myself, so I just committed updates to _**all**_ of your "performance" tests _(**CLCLE-04**-performance.asm, **TRE-02**-performance.asm, **TRTE-02**-performance.asm and **TRTRE-02**-performance.asm)_ to use a simple set of macros instead (example below):

https://github.com/SDL-Hercules-390/hyperion/blob/4e0d31e970d8299d8a84bc5cd911332fb547c743/tests/TRTRE-02-performance.asm#L195-L226

https://github.com/SDL-Hercules-390/hyperion/blob/4e0d31e970d8299d8a84bc5cd911332fb547c743/tests/TRTRE-02-performance.asm#L236-L246

https://github.com/SDL-Hercules-390/hyperion/blob/4e0d31e970d8299d8a84bc5cd911332fb547c743/tests/TRTRE-02-performance.asm#L259-L269

This should _hopefully_ fix the problem once and for all.

So you can go ahead and withdraw/delete/close this new Pull Request of yours, because it's _not_ going to be accepted, since your proposed "fix" (except for `dfp.c` which I'll do myself shortly) _has already been implemented!_ &nbsp;`;-)`
&nbsp;

**Review by Fish-Git — COMMENTED** [review]
REJECTED for reasons already outlined in previous comment.

**Comment by Fish-Git** [comment]
p.s. I also generated the PDFs using your preferred "Fira Code Medium" 11pt. font without the feedholes too, just to be nice. &nbsp;`;-)`

**Comment by Fish-Git** [comment]
> 1. remove a build GCC uninitialized warning message in dfp.c.

p.s. You might consider using `clang` instead of `gcc`. &nbsp;It's a much better compiler IMHO.

**Comment by JamesWekel** [comment]
Thanks Fish. I should have thought of using a macro to generate the instructions!

Jim

**Pull request closed without merging**
