### PR TITLE
Multiple things :

### PR DESCRIPTION
**Pull request by ivan-w**
- Upgrade libtool(ize)
- Add libhercu to hercules standalone (because of dependenency on new hscutl dependency)
- Small comsmetic change to workaround new libtoolize version (a bug will be opened on their end)
- autogen.sh run
- Attempt to run and build on freebsd 13

### CODE REVIEW

**Comment by Fish-Git** [comment]
Ivan,

Can you tell us why you feel your proposed changes are necessary?

One thing I noticed right away was the addition of many files consisting of only a single statement, with that one statement being just a path. For example, file "libltdl/libltdl/lt__alloc.h" contains only:
```
/usr/share/libtool/libltdl/lt__alloc.h
```

Nothing else! Why do we need that file added to Hercules?

Other files, such as "autoconf/config.guess", have had their _entire content deleted(!)_ and replaced instead with e.g.:
```
/usr/share/libtool/build-aux/config.guess
```

Why?!

Finally, some of the changes to other files don't exactly make any sense. In our "configure.ac" file for example -- a very important file! -- you are changing _comment_ statements containing the string "Makefile.am" to "Makefile.a m:" instead! (i.e. you are inserting a single blank between the ".a" and the "m". Why?!)

Are you _sure_ your proposed changes are correct and actually needed?

Because if you are, then I think you're going to need to explain them a little better because I'm having a hard time understanding them! &nbsp; `:(`

Thanks.

**Comment by wrljet** [comment]
> Other files, such as "autoconf/config.guess", have had their _entire content deleted(!)_ and replaced instead with e.g.:
> 
> ```
> /usr/share/libtool/build-aux/config.guess
> ```
> 
> Why?!

One comment on that...

If you look back in the last few commits, I updated our `autoconf/config.guess` and `autoconf/config.sub` to the (then) latest from GNU.  This is _part_ of my efforts to make things work on the Apple Mac with their M1 CPU.

This change replacing our local copies of those files with symlinks to what's installed on the system means we lose control of that.

Bill

**Comment by Fish-Git** [comment]
> This change replacing our local copies of those files with symlinks to what's installed on the system means we lose control of that.

So what you're saying is, all of these files that _appear_ to be having their entire content deleted and replaced with a single directory path statement, are actually _symlinks?_

_&lt;me: checks file's git properties...&gt;_

Wow. You're right! They _are_ symlinks!

Okay. Ivan's change now makes a lot more sense to me. Thanks, Bill.

Given what you've written however, I would tend to agree with you that his proposed changes should unfortunately probably be rejected. (Sorry, Ivan!)

**Review by Fish-Git — CHANGES_REQUESTED** [review]
Hi Ivan!

I myself cannot agree to your proposed changes due to what Bill Lewis said regarding them:

* https://github.com/SDL-Hercules-390/hyperion/pull/359#issuecomment-757672572

I would like to suggest that maybe the two of you should work together on making whatever changes both of you feel should be made such that each's does not negatively impact the other's.

**Comment by wrljet** [comment]
`config.guess` and `config.sub` symlinks appear to me to be completely independent of the rest of these changes.

I think we first need to understand what the intention is and what it fixes.
Which from the comments, I *assume*, is to upgrade `libtool` in an attempt to run and build on FreeBSD 13.

**Comment by Fish-Git** [comment]
Hi Ivan! &nbsp; (@ivan-w)

Have not heard back from you since both Bill and I left comments(*) regarding your Pull Request. I hope everything is okay!

Anyway, since it appears you have not made our requested changes to your pull request, I am unfortunately going to have to reject it at this time. &nbsp; `:(`
___
(*) Please see the following comments:
* https://github.com/SDL-Hercules-390/hyperion/pull/359#issuecomment-757511645
* https://github.com/SDL-Hercules-390/hyperion/pull/359#issuecomment-757672572
* https://github.com/SDL-Hercules-390/hyperion/pull/359#pullrequestreview-565111341

**Pull request closed without merging**
