### PR TITLE
macOS utun support

### PR DESCRIPTION
**Pull request by atncsj6h**
take a look at the modifications for utun support
TESTED, ping, ftp, TSO logon

PC1 < zOS1
zOS1 > PC1
I lost the docs to test for 
PC2 to  zOS1
zOS1 to PC2  
zOS1 to zOS2
I will just have to adjust the route and arp tables

Bill
here you will find the binaries for macOS  arm
with the checksum and my signature 
( just remember the chown and chmod for hercifc and hercutun )

https://drive.google.com/drive/folders/1CBI2LTpvTfuDbFckpLRJ-Y4lAOZjgiXJ

built in a clean repo after the commit and push to 

hope that this will a nice easter egg for the fans of Apple and Hercules

enrico

### CODE REVIEW

**Comment by atncsj6h** [comment]
is anybody going to take a look ???

**Comment by Fish-Git** [comment]
> is anybody going to take a look ???

Looking at it now (the code anyway), and I'm seeing some issues.

More later once I finish my review, which will probably take me a while (more than a day, possibly longer).

**Comment by atncsj6h** [comment]
Hi Fish 
I knew that there would have been a few/many issues 
I was not sure that the request had been noticed ...
take Your time,
thank you 
enrico

**Comment by Fish-Git** [comment]
> I was not sure that the request had been noticed ...

I of course cannot speak for any of the other developers, but I am subscribed to Pull Requests as well as Issues too, so I receive an email notification any time someone creates a new GitHub Issue or Pull Request as well as whenever anyone posts a new comment to either.

I might not immediately respond to the PR or Issue, but I usually do so within at a few days. What I'm saying is rest assured your Pull Request _was_ noticed ny at least myself, and from the looks of it, by Bill as well.

Whether it was noticed by any of the other developers or not, I cannot say.

**Comment by ezplanet** [comment]
So this was close without being merged and macOS users are still waiting for networking support. What a waste!

**Pull request closed without merging**
