### PR TITLE
add continuous integration via Travis CI with .travis.yml

### PR DESCRIPTION
**Pull request by wfjm**
I've setup [Travis CI](https://travis-ci.org/) integration for hyperion. The pull provides the `.travis.yml` file, which describes
- the build matrix, covering gcc 4.8, 5.x, 6.x, 7.x and clang 5.x
- the required packages (`regina-rexx` as provided by Ubuntu)
- the build script, simply `make` and `make check`

To make it work, you have first to sign up with Travis, best via the GitHub account, and than to activate tracking of the hyperion repository. If it is working, it is customary to add the `build badge` to the `README`. Hope you enjoy continuous integration.

Travis CI log of the last build for my fork of hyperion before writing the pull request can be inspected under https://travis-ci.org/wfjm/hyperion/builds/420555079 .

### CODE REVIEW

**Comment by wfjm** [comment]
Another remark:
the first round of Travis CI tests was done based on commit ffa4e27.  In those runs 11 tests failed, like
```
  Test "cipher 20161202 12.03":  93 OK compares.  212 failures.
  Test "digest 20161202 12.03":  36 OK compares.  21 failures.
  Test "Initial control register values":  0 OK compares.  9 failures.
  Test "ilc":  2 OK compares.  One failure.
  Test "mhi":  1 OK compares.  3 failures.
  Test "privopgo":  2 OK compares.  One failure.
  Test "semipriv":  4 OK compares.  One failure.
  Test "sske#2":  48 OK compares.  5 failures.
  Test "STFL and STFLE":  8 OK compares.  4 failures.
```
That was apparently fixed with commit 46b2782. I use nevertheless `regina_rexx`, simply because this is provided _out-of-the-box_ and package for Debian and Ubuntu.

**Comment by Fish-Git** [comment]
Can you try again? I made another commit (d73fe15a707b5601eb86de2bdd84b39c6b014b98) which _should_ resolve the issue of `make check` failing when Regina is used.

**Comment by Fish-Git** [comment]
p.s. I don't know a lot about Travis, but the following ".travis.yml" fragment doesn't seem right to me:
```
before_script:
  - util/bldlvlck
  - ./autogen.sh
  - ./configure 
```
Shouldn't the ./configure be: `./configure --enable-regina-rexx`? Otherwise the Hercules that is built won't have _any_ Rexx support! (_regardless_ of whether it is installed or not!)

**Comment by wfjm** [comment]
I've checked commit d73fe15, and it indeed resolves the Regina issue.

When I tried to `rebase` the development branch git refused to do so. The culprit is a CRLF issue, see pull request #142 for details. Before this is fixed I'm stuck in the `dev_travis` branch, in fact everybody else working on Linux too when using development branches.

Your remark on `--enable-regina-rexx` is well taken, will be changed.

**Comment by Fish-Git** [comment]
> Before this is fixed I'm stuck in the dev_travis branch, in fact everybody else working on Linux too when using development branches.

Pull Request accepted and Merged! THANKS! It was occassional causing me problems too but I could never figure out what was going on.

**Comment by wfjm** [comment]
I had to delete the branch, which closes this pull request, because I found no way to rebase it, even after #142 was merged. I've re-created the branch `dev_travis` , now based on 32f0176, and the Travis CI matrix finished without error, see [build 12](https://travis-ci.org/wfjm/hyperion/builds/423349077?utm_source=github_status&utm_medium=notification). I'll open a new pull.

**Pull request closed without merging**
