### PR TITLE
Add tests for AP,SP instructions

### PR DESCRIPTION
**Pull request by 76bav**
basic + performance test

### CODE REVIEW

**Comment by Fish-Git** [comment]
Andrey,

What is the reason these tests were created? Do you plan to optimize the instructions? I was not aware that either one had any issues.

**Comment by 76bav** [comment]
Hi David,
Yes, I want to optimize these instructions. I expect speed up two times and more on x86-64, depends on CPU.
Fist implementation will be for compiler that support **int128** (**GCC**, **Clang**). 

Best regards
Andrey.

**Review by Fish-Git — CHANGES_REQUESTED** [review]
I have decided to REJECT and CLOSE this Pull Request, as IMO it's not needed at this time.

I would expect that once you have actually completed your actual performance improvements themselves, that you would then include these tests as part of _that_ Pull Request too.

That is to say: Your future Pull Request should include _both_ your performance improvements _AND_ these tests too.

Thanks.

**Comment by Fish-Git** [comment]
Closing (rejecting) this PR. &nbsp;See my most recent comment as to why.

**Comment by 76bav** [comment]
> I have decided to REJECT and CLOSE this Pull Request, as IMO it's not needed at this time.
> 
> I would expect that once you have actually completed your actual performance improvements themselves, that you would then include these tests as part of _that_ Pull Request too.
> 
> That is to say: Your future Pull Request should include _both_ your performance improvements _AND_ these tests too.
> 
> Thanks.

Ok.

**Pull request closed without merging**
