### PR TITLE
Dfp 080

### PR DESCRIPTION
**Pull request by JamesWekel**
Fish,

Here is my attempt at the Decimal Floating Point Packed Conversion facility (080) instructions. Thank you for all the documentation on making Hyperion and adding new files to the solution. I used your recent  BEAR-Enhancement Facility commit as an outline so I hope that I've make all the correct additions/changes.

I still have lot of rust on my skillset but this was an interesting challenge to dig into such a large solution. So, make any changes as I'm sure that I've missed something.

Thanks,
Jim

### CODE REVIEW

**Review by Fish-Git — CHANGES_REQUESTED** [review]
Hi Jim!

I've reviewed your changes closely, and while I think you did a fantastic job _(I'm actually quite impressed!)_, I'm afraid I'm going to have to reject this PR for the following reasons:

1. Your code fails to compile on Windows using the version of Microsoft's Visual C/C++ compiler that I'm still using. I did not bother to check whether it compiled cleanly or not using the latest version of Visual Studio, since, even if it did, it's still not standard 'C' code (unless the standards changed recently, and even if they had, Hercules still needs to support older compilers).<br><br>The problem is lines 1561 and 1565 of `dfp.c`: you're using what appears to be a GCC extension that was **[expressly rejected by the C99 standards committee](https://stackoverflow.com/questions/18244726/why-doesnt-c-have-binary-literals)**.

2. Your "dfp-080-to-packed" (CPDT, CPXT) runtest verification test programs fails to verify. I'm getting _"Test "dfp-080-to-packed.tst:   CPDT, CPXT":  72 OK compares.  **320 failures**."_ Note that I tried both `0xF : 0xC` and `0x0F : 0x0C` for #<span>1</span> above, but the test still fails the same way:
* [dfp-080-tst-Tests-64-release.log](https://github.com/SDL-Hercules-390/hyperion/files/9387635/dfp-080-tst-Tests-64-release.log)

If you can correct the above two issues I would be _very_ happy to accept your Pull Request and merge it into our repository!
&nbsp;

**Comment by JamesWekel** [comment]
Fish,

Thank you for the review and finding issues for me to fix! 
  1. I have replaced the "0b1111 : 0b1100' with " 0x0F : 0x0C" to conform to the C99 standards.  VS 2022 msvc accepts 0b 
     constants and I'll try to avoid them in the future.
  
  2. The dfp-080-to-packed.tst was missing "$(testpath)/" so nothing to test! 
  
Hoping that try #2 works.

Thanks again,
Jim

**Review by Fish-Git — APPROVED** [review]
Looks good to me!

> _Test "dfp-080-from-packed.tst:   CDPT, CXPT":  162 OK compares.  **All pass**._
> _Test "dfp-080-to-packed.tst:   CPDT, CPXT":  393 OK compares.  **All pass**._
> _Did 2 tests.  **All OK**._

Will merge ASAP!

THANKS! &nbsp; `:))`

**Comment by wrljet** [comment]
Very nice work on this.  Thank you for your contribution.

Bill

**Pull request merged**
