### PR TITLE
Fix build errors on some machines. 

### PR DESCRIPTION
**Pull request by mtalexander**
Undefined external symbols _fetch_qw_noswap and _store_qw_noswap.

### CODE REVIEW

**Review by Fish-Git — CHANGES_REQUESTED** [review]
MUCH better! Thank you!

However, you're missing the last 2 most recent commits that I made to the develop branch yesterday (July 4th): the two HTML files: `hercnot.html` and `hercfaq.html`.

So you just need to do a quick `git pull` on what you've already got and everything _should_ be copacetic.

OR... since the only thing you are wanting to change is the addition of a few `#undef`s in `machdep.c`, I can certainly make that change for you myself and give you full credit as the Author. (That is to say, the change will appear in our commit log under _your_ name, not mine.)

Personally, I'd prefer that you simply do the pull to bring your repo current. That way I can accept your Pull Request.

But it's your choice.

**Comment by wrljet** [comment]
Works for me on Mac Mini M1, on macOS 14.5 with Clang 15.

**Comment by Fish-Git** [comment]
> Works for me on Mac Mini M1, on macOS 14.5 with Clang 15.

How did you do it? Did you do a merge? Or did you just manually apply his `machdep.c` changes? (which AFAIK are the only changes he is wanting to make?)

My concern, Bill, is whether the difference between his repository's verion of the two mentioned `.html` files will undo my previous commit or not. If they won't, then I can accept his Pull Request right now, as-is. But I don't want his Pull Request to undo anything that we've (I've) already done! Thus I'd be more comfortable if his repo was "current" (i.e. matched current 'develop'). Thus the request for a simple git pull to bring it current so its commits matches ours.

**Comment by Fish-Git** [comment]
And _now_ it looks like he has indeed pulled in the .html changes, but James just committed a change to `zvector2.c` just today which he's missing.

I realize it's a PITA when the repo you're trying to create your Pull Request from keeps changing, but that's simply an unavoidable circumstance that you sometimes have to deal with. We can't ask others to stop their own development efforts just because someone else is wanting to Pull their own changes into the repo. (Well, I suppose we _could_, but it doesn't seem right somehow.)

**Comment by wrljet** [comment]
Fish,

> > Works for me on Mac Mini M1, on macOS 14.5 with Clang 15.
> 
> How did you do it? Did you do a merge? Or did you just manually apply his `machdep.c` changes? (which AFAIK are the only changes he is wanting to make?)
> 
> My concern, Bill, is whether the difference between his repository's version of the two mentioned `.html` files will undo my previous commit or not. If they won't, then I can accept his Pull Request right now, as-is. But I don't want his Pull Request to undo anything that we've (I've) already done! Thus I'd be more comfortable if his repo was "current" (i.e. matched current 'develop'). Thus the request for a simple git pull to bring it current so its commits matches ours.

I just edited `machdep.c` by hand on top of what I cloned/checked-out shortly before I posted the comment here.

I didn't look at anything else.

You know I'm nervous with git and GitHub so I can't answer your question about undoing your/other more recent changes.

Bill

**Comment by mtalexander** [comment]
My Fix_qw2 branch is now completely up to date with develop and has been since about midnight Friday night.  I don't think there is anything more that I can do at this point.  Since I only changed one file and no one else has changed it in the last few days, this pull request is unlikely to have any nasty side effects.

**Review by Fish-Git — APPROVED** [review]
Accepted! Thanks, Mike. And sorry about all the hassle.

**Comment by Fish-Git** [comment]
Merged!

**Pull request merged**
