### PR TITLE
Zvector E6 instruction Tests

### PR DESCRIPTION
**Pull request by JamesWekel**
Fish,

A Large pull request... tests for instructions in zvector2.c. The next question is are the tests valid or are they just confirming what has been coded? Right now, it's the probably the 2nd option but it's a start.

I hope that the Hercules_VS.... files are correct. 

On Linux, 'make check' executes the 16 zvector-e6-... tests and on windows, Bill's hercules-helper builds the branch and executes the tests. 

Always appreciates comments.

No rush.

Jim

### CODE REVIEW

**Comment by Fish-Git** [comment]
> The next question is are the tests valid or are they just confirming what has been coded?

Yes, that is indeed the critical question. We need to verify the accuracy of the tests on real hardware.

I know that some of our fellow Hercules developers have zPDT systems, so that would be a good place to start I should think. But I'd of course feel much better if we could verify them on actual real iron and not just on another emulator. But let me first take a look at what you got.

> I hope that the Hercules_VS.... files are correct.

I'm sure they are, but let me take a look see.

> On Linux, 'make check' executes the 16 zvector-e6-... tests and on windows, Bill's hercules-helper builds the branch and executes the tests.

That's good to know. But you should also be able to run any one of our many tests manually by themselves (i.e. individually on demand) too, of course. I'll take a look at that too.

> Always appreciates comments.

Let me give what you've got the once over and I'll get back to you.

**Review by Fish-Git — CHANGES_REQUESTED** [review]
> I hope that the Hercules_VS.... files are correct.

Please fix:

```
    <ClCompile Include="zvector.c">
      <Filter>Source Files</Filter>  <----- needs fixed to be the same as zvector2!
    </ClCompile>
    <ClCompile Include="zvector2.c">
      <Filter>Source Files\Hercules\Emulation\Source Files</Filter>
    </ClCompile>
```

**Comment by JamesWekel** [comment]
[mcisho]( https://github.com/mcisho): I'll action Fish's request with another commit to update zvector.c Visual Studio location.

Fish, [mcisho]( https://github.com/mcisho) has updated sharedvfp with another commit, so you might see more file differences.

Jim

**Review by Fish-Git — APPROVED** [review]
Thank you for fixing the vcxproj.filters.

APPROVED.

(It'll be interesting to see what the results of the Merge are.)

**Comment by JamesWekel** [comment]
Thanks Fish.

The next instructions are floating point, so it is likely going to be a while before another pull request. 

Jim

**Pull request merged**
