### PR TITLE
Remove/silence all warning for gcc. 4 left for clang (but it may be a…

### PR DESCRIPTION
**Pull request by ivan-w**
… clang bug: `-Wno-unused-local-typedef[s]` has no effect.

Fish, anyone.. This affects multiple files.

Can this be checked?

Thanks,

--Ivan

### CODE REVIEW

**Comment by wrljet** [comment]
There are still a few gcc warnings with gcc 4.85 (tested on CentOS 7.8).

```
cpu.c: In function 's370_run_cpu':
cpu.c:1888:18: warning: variable 'regs' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
 register REGS   *regs;
                  ^
In file included from cpu.c:2211:0:
cpu.c: In function 's390_run_cpu':
cpu.c:1888:18: warning: variable 'regs' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
 register REGS   *regs;
                  ^
In file included from cpu.c:2217:0:
cpu.c: In function 'z900_run_cpu':
cpu.c:1888:18: warning: variable 'regs' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
 register REGS   *regs;
```

```
hscmisc.c: In function 's370_virt_to_real':
hscmisc.c:99:35: warning: argument 'arn' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
                               int arn, REGS* iregs, int acctype )
                                   ^
In file included from hscmisc.c:1155:0:
hscmisc.c: In function 's390_virt_to_real':
hscmisc.c:99:35: warning: argument 'arn' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
                               int arn, REGS* iregs, int acctype )
                                   ^
In file included from hscmisc.c:1161:0:
hscmisc.c: In function 'z900_virt_to_real':
hscmisc.c:99:35: warning: argument 'arn' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
                               int arn, REGS* iregs, int acctype )
```

```
In file included from sie.c:1810:0:
sie.c: In function 's390_start_interpretive_execution':
sie.c:291:5: warning: variable 'lpsw_xcode' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
 int lpsw_xcode;                         /* xcode from load_psw       */
     ^
In file included from sie.c:1816:0:
sie.c: In function 'z900_start_interpretive_execution':
sie.c:291:5: warning: variable 'lpsw_xcode' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
 int lpsw_xcode;                         /* xcode from load_psw       */
```

Bill

**Comment by Fish-Git** [comment]
> There are still a few gcc warnings with gcc 4.85 (tested on CentOS 7.8).
> 
> ```
> cpu.c: In function 's370_run_cpu':
> cpu.c:1888:18: warning: variable 'regs' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
>  register REGS   *regs;
>                   ^
> ```

Hi Bill!

IIRC we at one point determined that fixing these "clobber" warnings was probably more trouble than it was worth, so we decided to just live with them.

If you can figure out how to easily/elegantly eliminate them however, I'm all for it!

p.s. Check your email. There's an early Christmas present waiting for you in your inbox! &nbsp; `;-)`

**Review by Fish-Git — CHANGES_REQUESTED** [review]
_(Oops! I think I might have accidentally submitted my "Request for changes" without actually identifying the changes I would prefer that you make! Sorry! I'm sort of new at responding to requests for review of Pull Requests!)_

I would personally prefer that instead of `snprintf`, that `MSGBUF` be used instead -- _AS LONG AS_ the buffer is a fixed character array of course! _(hint: MSGBUF does _NOT_ work with char _pointer_ variables!)

The rest of your changes are non-controversial.

**Comment by ivan-w** [comment]
I started converting all the snprintf(x,sizeof(x),...) to MSGBUF(x) - and checking they are of the right type.. Still about 100 to go !

A bit tedious :P

**Comment by Fish-Git** [comment]
> I started converting all the `snprintf(x,sizeof(x),...)` to `MSGBUF(x)` - and checking they are of the right type.. Still about 100 to go!
> 
> A bit tedious   `:P`

Well for crying out loud, Ivan! I didn't mean for you to change _ALL_ `snprintf`s all throught Hercules to `MSGBUF`!! I was only talking about the two dozen or so ones shown in the files this Pull Request of yours was for! &nbsp; `(:-O`

But I do appreciate your diligence. &nbsp; `;-)`

**Comment by ivan-w** [comment]
Done (at least for those I could find)...

Please cross check ! Thanks !

--Ivan

**Review by Fish-Git — CHANGES_REQUESTED** [review]
Much better!

But still no good. &nbsp; `:(`

The _ONLY_ glitch that I could see is in `fet_write_header` function in file `ftlib.c`, where the faketape block header (`fakehdr`) is being built.

Because the fields defined in the `FAKETAPE_BLKHDR` struct are only _**4**_ chars in length each:

```C
    char  sprvblkl[4];                  /* length of previous block  */
    char  scurblkl[4];                  /* length of this block      */
    char  sxorblkl[4];                  /* XOR both lengths together */
```

your code that is doing a `MSGBUF` _directly into_ each of those fields, ends up formatting a string consisting of only _**3**_ ASCII hex characters followed by a null! (instead of the expected _**4**_ ASCII hex chars _period_).

Previous, the code was properly formatting the field values into an intermediate work field that was _**5**_ chars in size, and then `memcpy`ing that intermediate result into the header's 4-character field, thus ensuring the each header field was indeed the expected _non-null-terminated_ 4 ASCII character string:

```C
char            sblklen[5];             /* work buffer               */

    snprintf( sblklen, sizeof(sblklen), "%4.4X", prvblkl );
    memcpy( fakehdr.sprvblkl, sblklen, sizeof(fakehdr.sprvblkl) );
```

I suggest changing the original `snprintf`s to `MSGBUF` instead, removing the statements ensuring null termination (since they're not needed), and keeping only the `memcpy` statements that are copying the intermediate `sblklen` work buffer into the individual header fields.

Other than that however, everything else looks fine to me!

**Comment by ivan-w** [comment]
Done and understood ! Commit coming after I check it compiles !

**Review by Fish-Git — COMMENTED** [review]
Which is right? The comment? Or the #if statement? (One says >= 6, the other says >= 5)

**Comment by ivan-w** [comment]
The code is wrong ! apparently clang 5 supports -Wunused-local-typedef (the bug is that clang should support -Wunused-local-typedefs (plural) as an alias to -Wunused-local-typedef (clang only flag). This apparently exists at least up to (and incluing) clang 8.

**Review by Fish-Git — APPROVED** [review]

**Review by Fish-Git — CHANGES_REQUESTED** [review]
`faketape.c` looks okay, but `ftlib.c` still looks broken!

**Comment by ivan-w** [comment]
Got it ! Thank you (again) !

**Review by Fish-Git — APPROVED** [review]
Are we having fun yet? &nbsp; `:))`

APPROVED! COMMIT IT ALREADY! &nbsp; `:)`

(or Merge your Pull Request or _whatever..._)

_OR..._ &nbsp; I of course can do it if you want, but seriously, _any_ of us developers can accept someone's Pull Request. There's no real need (requirement) for someone else doing it. We _ALL_ have commit authority to the repository after all.

**Comment by ivan-w** [comment]
Various changes addressing warnings and refactoring to use MSGBUF instead of snprintf whenever possible

**Comment by wrljet** [comment]
And I'm dreading my first major screw up. :-)

**Comment by ivan-w** [comment]
Don't worry Bill ! That's the beauty of git.. Nothing is ever lost.. The only minor risk is feeling embarrassed (looking in the mirror here)

**Comment by Fish-Git** [comment]
What Ivan said. &nbsp; `:)`

**Pull request merged**
