### PR TITLE
Check tracing flag before function call.

### PR DESCRIPTION
**Pull request by 76bav**
This removes some overheat of stack operations.

### CODE REVIEW

**Review by Fish-Git — CHANGES_REQUESTED** [review]
***ONE*** minor change requested: line 1600 of `sie.c`: leave it alone! You appear to have replaced the single apostrophe with some weird unicode character! Please put it back to the way it was.

Everything else looks great! Thanks!

**Review by Fish-Git — APPROVED** [review]
Thanks! Looks good!

**Comment by 76bav** [comment]
Hi David.
Originally, it's not a simple apostrophe, I think. By that reason it was changed by Git Hub Desktop, I don't touch it by hand.
After that I try to revert it, but without success (.
Now I change it to simple apostrophe, but the change is visible anyway.

Best regards Andrey.

**Comment by Fish-Git** [comment]
> Originally, it's not a simple apostrophe, I think.

After closer inspection, it appear you are correct! My apologies.

> Now I change it to simple apostrophe, but the change is visible anyway.

That's fine. That's what it's _supposed_ to be anyway! &nbsp;`:)`

In any case, your PR was accepted and merged.

Thanks again.

**Pull request merged**
