### PR TITLE
vr command: Display or alter vector registers

### PR DESCRIPTION
**Pull request by salva-rczero**
I think these are the last changes to Hercules facilities in general, before I start contributing vector instruction execution code to zvector.c.

Regards, salva.

### CODE REVIEW

**Review by Fish-Git — CHANGES_REQUESTED** [review]
I'm not done with my review yet, but I noticed something that merits an immediate rejection: tabs!

NO TABS!

Please use spaces instead.

Other than that, everything else is looking good!

But as I said, I'm not done yet...

**Review by Fish-Git — COMMENTED** [review]
Syntactically, technically  and logically, everything looks fine! There are a few places where the style you use doesn't match the existing style, but that's just a personal thing, so I'm not going to ask you to change it _(although I would certainly appreciate it if you did)_.

* [salva.zip: &nbsp;Suggested _(but not required)_ changes](https://github.com/SDL-Hercules-390/hyperion/files/15132015/salva.zip)

&nbsp;

**Review by Fish-Git — APPROVED** [review]
THANK YOU!

Optional _suggested_ changes:

* [salva2.zip](https://github.com/SDL-Hercules-390/hyperion/files/15132267/salva2.zip)

**Comment by salva-rczero** [comment]
Thanks @Fish-Git. Sorry for the TABs, I changed my editor to always replace tabs with spaces, but something scaped.

**Pull request merged**
