### PR TITLE
Initial Z/Vector E6 instructions

### PR DESCRIPTION
**Pull request by JamesWekel**
An initial cut to introduce the Z/vector E6 instructions into the sharedvfp branch. Even though zvector2.c is still under development and needs significant changes to handle Decimal overflow, missing instructions, etc., I'm looking to merge changes into instruction handling infrastructure and avoid manual merge reconciliation to get back in sync with changes in the branch.       

At this point, I'm my testing has been only on Linux.

VM/Community Edition 1.2 ipl'ed and I could logon to CMS, so I'm hoping that I got the overlapped instruction codes for Z/Vector E6 and ECPSVM E6 instructions.   

ALL comments are welcome. 

Jim

### CODE REVIEW

**Comment by JamesWekel** [comment]
Fish,  not sure how I have one of your commits in my pull request.   

Jim

**Review by Fish-Git — CHANGES_REQUESTED** [review]
_____________________

_**Windows errors:**_

* [error C2065: 'i' : undeclared identifier](https://github.com/JamesWekel/hyperion/blob/7f1b9c3509c09c6c5f365184c034416457af8192/ieee.c#L1519)<br>I think maybe it should be `0` instead of `i`?
* [error C4101: 'op1' : unreferenced local variable](https://github.com/JamesWekel/hyperion/blob/7f1b9c3509c09c6c5f365184c034416457af8192/ieee.c#L1670)<br>There are _many_ of these!
* [error LNK2001: unresolved external symbol z900_vector_shift_and_divide_decimal](https://github.com/JamesWekel/hyperion/blob/7f1b9c3509c09c6c5f365184c034416457af8192/msvc.makefile.includes/OBJ_CODE.msvc#L156)<br>You forgot to add `$(O)zvector2.obj` to `OBJ_CODE.msvc`.
* [error C2275: '__m128i' : illegal use of this type as an expression](https://github.com/JamesWekel/hyperion/blob/7f1b9c3509c09c6c5f365184c034416457af8192/zvector2.c#L172)<br>I fixed it by replacing your statement with the following two statements instead:<br>`__m128i v = _mm_setzero_si128();`<br>`memcpy( addr, &v, sizeof( __m128i ));`

All of the above Windows build errors are fixed in the below patch:

* [zvector-E6.zip](https://github.com/SDL-Hercules-390/hyperion/files/15329112/zvector-E6.zip)

_____________________

_**clang warnings:**_

[ieee.c:2109:43: warning: overlapping comparisons always evaluate to true](https://github.com/JamesWekel/hyperion/blob/7f1b9c3509c09c6c5f365184c034416457af8192/ieee.c#L2109)
[ieee.c:2174:43: warning: overlapping comparisons always evaluate to true](https://github.com/JamesWekel/hyperion/blob/7f1b9c3509c09c6c5f365184c034416457af8192/ieee.c#L2174)

[zvector.c:1678:5: warning: variable 'ind1' is used uninitialized whenever switch default is taken
zvector.c:1678:5: warning: variable 'ind2' is used uninitialized whenever switch default is taken](https://github.com/JamesWekel/hyperion/blob/7f1b9c3509c09c6c5f365184c034416457af8192/zvector.c#L1682)<br>(Oops?)

[zvector.c:1763:5: warning: variable 'ind1' is used uninitialized whenever switch default is taken
zvector.c:1763:5: warning: variable 'ind2' is used uninitialized whenever switch default is taken](https://github.com/JamesWekel/hyperion/blob/7f1b9c3509c09c6c5f365184c034416457af8192/zvector.c#L1767)<br>(Oops?)

[zvector.c:2955:36: warning: array index -1 is before the beginning of the array](https://github.com/JamesWekel/hyperion/blob/7f1b9c3509c09c6c5f365184c034416457af8192/zvector.c#L2955)<br>I think maybe it should be '1' instead of '2'??.

_____________________

I did _not_ try to fix any of the above clang warnings. &nbsp; I leave that to you.

&nbsp;

**Comment by JamesWekel** [comment]
[mcisho](https://github.com/mcisho) 

Note a compile error with ieee.c:

```
ieee.c: In function ‘z900_vector_fp_load_lengthened’:
ieee.c:1519:42: error: ‘i’ undeclared (first use in this function)
 1519 |         GET_VECTOR_FLOAT64_OP(  op2, v2, i, regs );
[
```
and the windows build errors that Fish has identified in [zvector-E6.zip](https://github.com/SDL-Hercules-390/hyperion/files/15329112/zvector-E6.zip)

Fish,
    1. [mcisho](https://github.com/mcisho) is working on ieee.c and zvector.c so I'll defer your comments to him.
    2. I was trying a Windows build using hercules-helper (while you were doing your review!) and noticed that zvector2 was missing so that was a short fix. Thanks for the intrinsic update. Until zvector2.c is finished, I'm not going to include any more intrinsic use.
    3.   Since it doesn't build on windows, it's a bit hard to test!! 
   
Thanks for the help.

Jim

**Comment by mcisho** [comment]
Aren't compilers a pita? Clang on Linux was quite happy the defines weren't there. I have done commits to resolve the ieee.c error and warnings (and many other changes that move the code forward). I haven't looked at the zvector.c warnings, they can wait awhile (imho!).

**Comment by Fish-Git** [comment]
> Aren't compilers a pita?

Indubitably!

But this is of course part of the general PITA that portability itself entails. If we didn't care about operating system portability then things would be easy. We could target our product to just one operating system and one compiler. But as a consequence of our desired for our product to be portable across multiple operating systems and multiple compilers, such pita issues will always remain a part of our lives as Hercules developers. We may not like it, but unfortunately it is something we will have to continue to deal with as best we can.

**Comment by JamesWekel** [comment]
Fish,

With [mcisho](https://github.com/mcisho)'s commits to the sharedvfp branch, the commits & pull request now compile on both windows and Linux. Are there any add additional changes that you recommend for this request?

Thanks,
Jim

**Comment by Fish-Git** [comment]
> With [mcisho](https://github.com/mcisho)'s commits to the sharedvfp branch, the commits & pull request now compile on both windows and Linux.

Not for me. &nbsp;`:(`

I pulled your latest commits to your fork:

* https://github.com/JamesWekel/hyperion/commit/531d64dbc9ee094a2f734a594ba6b6f9b33aadb6
* https://github.com/JamesWekel/hyperion/commit/a4ba5cadf3e103ffaf40fbd6a2723d5f044e6b03

and it _still **fails**_ to build on _both_ Windows _and_ Linux.

It looks like you only made _some_, but not _ALL_, of the requested changes that I listed earlier, but the other error/warnings still remain. The end result is, it unfortunately _STILL_ does not build successfully, neither on Windows _nor_ on Linux:

```
In file included from ./ieee.c:6991:
./ieee.c:1519:42: error: use of undeclared identifier 'i'
./ieee.c:1670:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1684:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1697:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1733:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1747:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1760:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1796:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1810:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1823:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1859:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1873:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1886:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1922:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1936:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1949:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1985:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:1999:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2012:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2048:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2062:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2075:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2117:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2130:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2143:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2182:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2195:21: warning: unused variable 'op1' [-Wunused-variable]
./ieee.c:2208:21: warning: unused variable 'op1' [-Wunused-variable]
27 warnings and 1 error generated.
make[2]: *** [Makefile:2637: ieee.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:2687: all-recursive] Error 1
make: *** [Makefile:2006: all] Error 2
```

I'm afraid I still cannot approve your Pull Request as it currently stands. Sorry! &nbsp;`:(`

> Are there any add additional changes that you recommend for this request?

Yes! &nbsp; See above.

**Comment by Fish-Git** [comment]
To be clear, Hercules's `sharedvfp` branch does indeed build cleanly on both Windows and Linux.

The `zvector-E6` branch of _YOUR_ repository (fork) however -- the branch of your fork with the changes you want me to merge (pull) into Hercules -- still does _**not**_.

**Comment by JamesWekel** [comment]
Fish, I've submitted a revised pull request. I'm closing this request.

Jim

**Comment by Fish-Git** [comment]
> Fish, I've submitted a revised pull request. I'm closing this request.

10-4. I'll take a look at you new request.

**Pull request closed without merging**
