### PR TITLE
add walking region/segment/page table to fix #185

### LINKED ISSUE #185: SCLP HWL / Store Data compatibility with zLinux
Hi,

First: I'm very much a newbie on the S390/Z architecture so forgive me if I do something stupid.

Now, something that caught my attention is the loader facility that Hercules calls HWL but IBM appears to be calling Store Data (as evident from [this commit](https://github.com/torvalds/linux/commit/66aec647216f129b8560dba738303a8486481c53#diff-9eeeb1dc96af1958582357af6be8eae7)).

The interface seems to provide blob access to what is referred to as "files". The ones I know of are:

- File 1: Coupling Facility Control Code (CFCC)
- File 2: SCSI Boot Loader
- File 3: Configuration of some sort (that's what the kernel commit above adds)
- File 7: Netboot (Unconfirmed, the only reference to this I find is [in Hercules](https://github.com/SDL-Hercules-390/hyperion/blob/54070a2f353313342d973d12c36425798d4e7dee/scescsi.c#L113))

As a side note I have reached out to the author of that patch set with the suggestion to add the other file types as well as it doesn't make much sense not to expose them I feel.

As I'm a curious person I wanted to see if I could use the SCLP SD interface contributed above to read an arbitrary file to an Ubuntu S390X VM running under Hercules. Turns out, I cannot. Which probably means that Hercules is not emulating something perfectly, or the Linux implementation is flawed. Whichever way, it's a nice win to figure it out.

# What's the environment?

- I run Ubuntu 18.04 Bionic with the latest 4.18 kernel. After installation it comes with 4.15 so it needs to be updated (`sudo apt-get install linux-image-4.18.0-15-generic`) and re-IPLd.
- I'm running a couple of days old Hyperion (7703dda3) with some custom tracing printouts added.

I have applied this patch to `scescsi.c` (manually cleaned up so it will not apply using `patch` but you get the idea):

```diff
diff --git a/scescsi.c b/scescsi.c
index 1754889b..29d1e423 100644
--- a/scescsi.c
+++ b/scescsi.c
@@ -89,7 +89,9 @@ typedef struct _SCCB_HWL_BK {
 #define SCCB_HWL_TYPE_RESET     0x01    /* Reset request             */
 #define SCCB_HWL_TYPE_INFO      0x02    /* Load info request         */
 /*007*/ BYTE    file;
 #define SCCB_HWL_FILE_SCSIBOOT  0x02    /* SCSI Boot Loader          */
+#define SCCB_HWL_FILE_CONFIG    0x03    /* Config Loader             */
 /*008*/ FWORD   resv1[2];
 /*010*/ FWORD   hwl;                    /* Pointer to HWL BK         */
 /*014*/ HWORD   resv2;
@@ -108,7 +110,9 @@ struct name2file {
 
 
 struct name2file n2flist[] = {
     { "scsiboot", SCCB_HWL_FILE_SCSIBOOT },
+    { "config",   SCCB_HWL_FILE_CONFIG },
 #if 0
     { "netboot",  7 }, // Hercules implementation of PXE style netboot for OSA
 #endif
```

[This ](https://gist.github.com/bluecmd/9490baa2a1b3c2a896e05083cdd45446) is my configuration for Hyperion.

`/usr/local/share/hercules/scsiboot` is the same file as `util/scsiboot` in this repository (hash checksum verified). The size is 4096 bytes.

# What's the issue 

This is how I trigger the issue from inside the Ubuntu VM:

```
root@ubuntu:/sys/firmware/sclp_sd/config# echo 1 > reload
root@ubuntu:/sys/firmware/sclp_sd/config# stat data
  File: data
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 14h/20d	Inode: 7271        Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-02-11 22:44:41.444374503 +0100
Modify: 2019-02-11 22:44:41.444374503 +0100
Change: 2019-02-11 22:44:41.444374503 +0100
 Birth: -
root@ubuntu:/sys/firmware/sclp_sd/config# dmesg | tail -n 1
[ 2678.416112] sclp_sd.aa051d: A 4096-byte config data entity was retrieved
root@ubuntu:/sys/firmware/sclp_sd/config# hexdump -C data
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00001000
root@ubuntu:/sys/firmware/sclp_sd/config# 
```

As you can see the size is transmitted successfully, However the file is only zeros inside the VM so no data was copied..

From my [trace output](https://gist.github.com/bluecmd/2762655d3486b8160fe7210bf063466b) it can be seen that Hercules tried to honor the copy but failed. My modifications to the `hwl_loadfile` function is included in that link as well.

Note this part:

```
TRACE pto: 24     
```
(That's 0x24, not decimal)

This means that the check for PAGETAB_INVALID (0x20) fails. I'm not sure why this page table would be marked as INVALID or what this means here.

# Debugging

PTO is constructed from what I can deduce is dereferencing STO, which is called SAT in the Linux code. Here is my very professional translation table to map what is what compared to Hercules' `_SCCB_HWL_BK`:

```c
struct sclp_sd_evbuf {                 
  ·struct evbuf_header hdr;             
  u8 eq; /* type */                    
  u8 di; /*file */                     
  u8 rflags; /* resv1[0] */               
  u64 :56; /* resv1[0] also */        
  u32 id; /* resv1[1] */               
  u16 :16; /* resv2 */                 
  u8 fmt; /* asa */                    
  u8 status; /* resv3 */               
  u64 sat; /* sto */                   
  u64 sa;  /* resv4[0] | resv4[1] */   
  u32 esize; /* resv4[2] */            
  u32 dsize; /* dsize */               
} __packed;    
```

In the relevant context SAT is called `asce` and is used as follows:

https://github.com/torvalds/linux/blob/66aec647216f129b8560dba738303a8486481c53/drivers/s390/char/sclp_sd.c#L309-L320

Following this deeper, the following function `base_asce_alloc` is called. Interestingly it appears to have been committed at the same time (Feb 22, 2018).

https://github.com/torvalds/linux/blob/aa0c38cf39de73bf7360a3da8f1707601261e518/arch/s390/mm/pgalloc.c#L630-L668

This function initializes the table with e.g. `_REGION3_ENTRY_EMPTY` for region 3 which just happens to evaluate to 0x24. So that's my current thinking is where the PTO value comes from.

So given the recent nature and the somewhat arcane uses of this config file, maybe this is a kernel bug?

I have it on good authority that IPLing SCSIBOOT from z/VM works when running under Hyperion, so this code is not totally broken - just this particular interaction seems to be a bit wonky.

A final note is that 4.18 from Ubuntu is of course not the same as 4.20 mainline, but compiling the Linux kernel in a VM running on Hercules is not exactly fast so I'm trying to figure out as much as I can without resorting to that.

### PR DESCRIPTION
**Pull request by mfsysprog**
this fix is to correctly load a config file fixing #185. I've tried a couple of files (of different length) and they all seem to be properly loaded. I have not been able to test the ESA-390 part of the code, but I've tried to make sure looking at the old code that it still will work. I also did not test the scsiboot, I don't know how that works, but it should still work.

### CODE REVIEW

**Comment by mfsysprog** [comment]
I see in the travis build that some builds fail on initializing the loop counter variable ```i``` inside the ```for``` statement.

```scescsi.c: In function 'base_region1_walk':

scescsi.c:343:4: error: 'for' loop initial declarations are only allowed in C99 mode

    for(unsigned int i = 0 ; i < entries  ; i++)
```
If I fix this by declaring the ```unsigned int i``` outside of the ``for`` loop and commit / push that change, will this retrigger the travis build and will this pull request automatically take that fix? I don't have that much experience with pull request.

**Comment by mfsysprog** [comment]
There is also an incompatible assignment in the ESA-390 mode that I will fix.
```
scescsi.c:255:11: warning: assignment from incompatible pointer type [enabled by default]

       ste = (DBLWRD*)(sysblk.mainstor + sto);
```

**Comment by mfsysprog** [comment]
> If I fix this by declaring the `unsigned int i` outside of the `for` loop and commit / push that change, will this retrigger the travis build and will this pull request automatically take that fix? I don't have that much experience with pull request.

I already figured out that I could just add another commit and push. Currently running travis builds, fingers crossed :-)

**Review by Fish-Git — APPROVED** [review]
Seems reasonable to me!

**Review by Fish-Git — CHANGES_REQUESTED** [review]
I take that back. This pull does _not_ look okay. It doesn't even compile! I can see what you're trying to do however. Let me see if I can fix your code to the way I believe it should be, and then I will submit _my_ version of your code to _you_ for review/approval.

p.s. How do I test it?

**Comment by mfsysprog** [comment]
Well, I'm certainly open to suggestions. But I had no problem compiling and also the travis runs compiled ok, so can you explain what part does not compile for you? I tested with a ubuntu 18.04 installation as described by the op of the original ticket.

**Comment by Fish-Git** [comment]
> Well, I'm certainly open to suggestions

Here's my (untested!) version of `scescsi.c`:

* [scescsi.c.txt](https://github.com/SDL-Hercules-390/hyperion/files/5648172/scescsi.c.txt)

(Note: you'll obviously need to rename it from "scescsi.c.txt" to just "scescsi.c". GitHub doesn't allow attaching .c files for some strange reason!)

> But I had no problem compiling and also the travis runs compiled ok

Well I don't know what the heck you or travis compiled, but it obviously _wasn't_ your code!

I cloned your repository (https://github.com/mfsysprog/hyperion-1) and the `scescsi.c` file in _your repository_ (which is ultimately what would be pulled into SDL Hyperion's repository) I'm seeing obvious errors that no C compiler on earth would accept:

```C
static void ARCH_DEP(base_segment_walk)(CREG sto, int fd, U32 size)
{
   /* we want to find valid page table origins */
   CREG pto;
   /* segment tables have 2048 entries max */
   /* tablelength 0 means 512 entries, 1 means 1024, etc. */
   unsigned int entries = ((sto & REGTAB_TL) + 1) * 512;
   /* remove bit definitions to form table origin */


#if defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)
   sto &= REGTAB_TO;
#else /*!defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)*/
   sto &= STD_STO;
#endif /*!defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)*/


#if defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)
    DBLWRD *ste;
#else /*!defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)*/
    FWORD *ste;
#endif /*!defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)*/


   /* walk trough all table entries to find valid items */
   unsigned int i;
   for(i = 0 ; i < entries  ; i++)
```
https://github.com/mfsysprog/hyperion-1/blob/ca65411d2f54ce01fb0f14802d5a63bb26a532bf/scescsi.c#L231-L254

In C, all variable declarations need to come _before **any** code_, and we clearly see your `DBLWRD *ste;` and `FWORD *ste;` statements -- as well as your `unsigned int i;` statement -- all coming _after_ your `sto &= REGTAB_TO;` and `sto &= STD_STO;` statements.

Like I said, there is NO COMPILER ON EARTH that would accept such a clear and obvious error.

I don't know what you and travis compiled, but it _wasn't_ your code! It was something else. Maybe you just compiled 4.3? (i.e. without your changes?)

But like I said, as it stands, I cannot accept this pull request. I'm sorry.

If my replacement code is acceptable to you (if you like it), I can go ahead and commit it under your name (i.e. I can commit my suggested code giving you credit as being the author instead of me).

But I don't know what else to do! Your changes are bad!

Sorry! &nbsp; `:(`

**Comment by mfsysprog** [comment]
I'm more that happy to accept your version of the code, it is the result that matters. I will test it today.

But having said that, I don't see the issue with the code part that you posted or why it would not compile?
The ```CREG sto``` comes in from the function header (where it is thus declared), it then goes to the following statement:
```unsigned int entries = ((sto & REGTAB_TL) + 1) * 512;```
that calculates the number of entries the table has.
Once we longer need those bits at the end to calculate the table length we can get rid of them:
```
#if defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)
   sto &= REGTAB_TO;
#else /*!defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)*/
   sto &= STD_STO;
#endif /*!defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)*/
```
this will do a bitwise AND on the sto to get the origin of the table, which basically is the first segment table entry.
At this point we declare the *ste because we are going to need it inside the loop that follows:
```
#if defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)
    DBLWRD *ste;
#else /*!defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)*/
    FWORD *ste;
#endif /*!defined(FEATURE_001_ZARCH_INSTALLED_FACILITY)*/
```
and we declare an unsigned int for the table loop:
```
   /* walk trough all table entries to find valid items */
   unsigned int i;
   for(i = 0 ; i < entries  ; i++)
```
I'm definitely not a very experienced c programmer, so if I made a mistake I don't have any issue admitting that, but I very sure in this case that the code I made will actually compile, at least on a linux system :-)

**Comment by mfsysprog** [comment]
Can you give me the definitions for the error messages that you added to ```msgenu.h``` for your version of the code?
It won't compile without them ;-)

**Comment by Fish-Git** [comment]
> Can you give me the definitions for the error messages that you added to `msgenu.h` for your version of the code?
> It won't compile without them ;-)

(Oops!) Sorry. Forgot about that. Here you go:

* [msgenu.h.txt](https://github.com/SDL-Hercules-390/hyperion/files/5648645/msgenu.h.txt)

```C
#define HHC00658 "I/O error on read(): rc=%d: \"%s\""
#define HHC00659 "%s is outside of main storage"
```

**Comment by mfsysprog** [comment]
I succesfully tested your code, no problems!
Shall we close this pull request, so you can send in your own fix?

**Comment by Fish-Git** [comment]
> succesfully tested your code, no problems!

Fantastic!

> Shall we close this pull request, so you can send in your own fix?

Sure. But first, who should get the credit? Should I commit my code under your name? (So you get credit for it?) Or should I commit it under my own name? I would prefer that _you_ get credit for the actual fix (since it was you that diagnosed the problem and figured out how to fix it), but I don't want you to be unfairly blamed for any problems there might be with my code either. So I will only commit it under your name with your express permission.

So... yes or no? Do you want me to commit my algorithm under your name as the author? Or would you rather me _not_ do that?

Let me know. It's your choice!

**Comment by mfsysprog** [comment]
I don't really care about if I get the code credit or not. I'm just happy I managed to figure out what was happening. So feel free to commit under my name, or under your own. Both options are fine with me.

**Comment by wrljet** [comment]
> https://github.com/mfsysprog/hyperion-1/blob/ca65411d2f54ce01fb0f14802d5a63bb26a532bf/scescsi.c#L231-L254
> 
> In C, all variable declarations need to come _before **any** code_, and we clearly see your `DBLWRD *ste;` and `FWORD *ste;` statements -- as well as your `unsigned int i;` statement -- all coming _after_ your `sto &= REGTAB_TO;` and `sto &= STD_STO;` statements.
> 
> Like I said, there is NO COMPILER ON EARTH that would accept such a clear and obvious error.

Fish,

That's not quite true.  Since the C99 standard, mixing declarations with code *is* allowed.

Microsoft has supported C99 style variable declarations since MSVC++ version 12 (Visual Studio 2013).
gcc supported that language feature far earlier.

I'm not suggesting any coding style change for Hercules here.  Just pointing out that is a feature of C
that has been around for a long time.

Bill

**Comment by Fish-Git** [comment]
> That's not quite true. Since the C99 standard, mixing declarations with code _is_ allowed.

_(Doh!)_ You are of course absolutely right. Thank you, Bill.

> Microsoft has supported C99 style variable declarations since MSVC++ version 12 (Visual Studio 2013). gcc supported that language feature far earlier.

Right again.

I can see I'm going to have to make a greater effort to try and upgrade my 12+ year old Visual Studio 2008 to a more modern version. I know I'm going to hate doing so (later versions of VStudio do _not_ impress me), but I can see my continued delay in doing so will only serve to cause more problems down the road, not less. &nbsp; `:(`

(sigh!) If only there was a way to just replace the _compiler_ part of my VS2008 install! Doing _that_ is absolutely something I wouldn't hesitate doing. I just don't want to lose my comfortable VS2008 user interface sweater, you know? &nbsp; `:)`

I'll have to do some research in that area....

**Comment by Fish-Git** [comment]
> I don't really care about if I get the code credit or not. I'm just happy I managed to figure out what was happening.

Me too! &nbsp; `:)`

> So feel free to commit under my name, or under your own. Both options are fine with me.

10-4. I'll make the commit right away and close this pull request once I do.

THANK YOU for the time and effort _(and patience with me!)_ you've spent working on this issue, Erik. _Mucho_ appreciated!

**Comment by Fish-Git** [comment]
The fix (commit b4c7fee88a0f3f7def2f0d2ea7663c55b5a704f6) has now been committed, so I am closing this pull request.

Thank you for your effort working on this issue, Erik! Much appreciated!

**Comment by Peter-J-Jansen** [comment]
The walking region/segment/page table fix had still a few errors around variables "pages" and "tables", which I've now corrected and tested, but hopefully without introducing other errors for Erik or Fish or others. Please let me know if that were to be the case. 

Thanks !

Peter

**Comment by Fish-Git** [comment]
Erik (@mfsysprog),

Can you do us a favor and do a git pull to pick up [Peter's commit](https://github.com/SDL-Hercules-390/hyperion/commit/b7f11e002c2aeaae521f1cd1b06c0beb08585fa0) and then do your test again please? Peter has made an [update to the hwl loader logic](https://github.com/SDL-Hercules-390/hyperion/pull/337#issuecomment-751338447) and we want to be sure he didn't accidentally break anything for you.

Thanks!

**Comment by mfsysprog** [comment]
Tested, it still works fine.

**Comment by mfsysprog** [comment]
One small observation, the ```HHC00661I Hardware loader SCCB =``` message will appear twice, since the first time the guest will do a ```SCCB_HWL_TYPE_INFO``` request to determine the size (in pages) of the file to be loaded into memory and the second time it will do a ```SCCB_HWL_TYPE_LOAD``` to request the actual load, but the message doesn't distinguish between the two types of requests. 
So testing with a config statement ```HWLDR   CONFIG   /usr/local/share/hercules/zzsacard.bin``` will show up as:
```
HHC00661I Hardware loader SCCB = 0x7FE4A000                                                                                                                                                                        
HHC00661I Hardware loader SCCB = 0x7FE4A000                                                                                                                                                                        
HHC00651I Loading /usr/local/share/hercules/zzsacard.bin   
```

**Comment by Fish-Git** [comment]
> Tested, it still works fine.

Thanks!

> One small observation, the `HHC00661I Hardware loader SCCB =` message will appear twice...

What do you suggest? Don't issue the message on an INFO request, and instead only issue it for a LOAD request? Or perhaps just a separate message number or message text? (e.g. identify what type of request it was, or use a different message number for INFO and a different one for LOAD?)

Either way is fine by me and would be a simple change to make. Let me know which you prefer. Thanks!

**Comment by mfsysprog** [comment]
I didn't add the messages, so I'm fine with whatever solution.

**Pull request closed without merging**
