### PR TITLE
Zvector E6 instruction updates

### PR DESCRIPTION
**Pull request by JamesWekel**
Fish,

Here is a new branch with the my updates and is current with sharedvfp branch. 

The fun of multiple concurrent and independent developers. Github indicates that branches can be automatically merged. :-)

Jim

### CODE REVIEW

**Review by Fish-Git — APPROVED** [review]
Much better!

I'm still somewhat confused about GitHub's "Files changed" reporting that only 2 files were changed however. Whenever I compare your repository's `zvector-E6-6` branch against Hercules's `sharedvfp` branch, it's showing that 4 files are different, not 2: `ieee.c`, `opcode.c`, `zvector.c`,  and `zvector2.c`.

So there's something about GitHub's Pull Requests that I'm not understanding. But I guess that's for another day to figure out.

I reviewed your changes (to all 4 files) and did not see anything that jumped out at me as being wrong, so your Pull Request looks good to me.

I kind of wish one of the other potential reviewers (@Juergen-Git and/or @Peter-J-Jansen) would also review Pull Requests on occasion, but that's okay. I'm not sure they're any more familiar with Vector instructions than I am, which is not at all!&nbsp;`:)`

APPROVED.

**Comment by JamesWekel** [comment]
Fish,

Thank you.  At times Git & Github confuse the H... out of me. I very cautious which is why I closed the old pull request, resynced the `sharedvfp` branch with my fork, created a new branch (`zvector-E6-6`), merged (Github pull) the old branch (`zvector-E6-5`) and then this pull request. Could it be part of this process that is causing 4 files to show changes when I only change two files: `opcode.c` and `zvector2.c`? 

The next pull request will be 16 tests and all their files.

Thanks again.
Jim

**Comment by Fish-Git** [comment]
> Could it be part of this process that is causing 4 files to show changes when I only change two files: `opcode.c` and `zvector2.c`?

I don't know. All I do know is that they're different (or WERE different).

I use a visual file comparison tool(*) that allows me to compare the files in one directory with those in another (or an individual file with another), and it reported that those 4 files were different. Comparing the files directly with one another showed that they were indeed quite different from one another. How that happened I don't know, but those 4 files _WERE_ different. Which is why I was wondering why GitHub was reporting that only 2 files were changed.

Maybe GitHub is only reporting which files were changed in the most recent commit? Maybe those other two files were modified in an earlier commit? I'm beginning to think that is the case. Which, for a Pull Request, is stupid. A Pull Request is a collection of modified files, so in my opinion, GitHub should be reporting how many files IN TOTAL are being changed by the Pull Request.

Regardless, I reviewed all 4 files (I reviewed EVERYTHING that would be modified by the Pull Request) and everything looked okay to me, so I approved your PR and did the merge to pull your changes into the sharedvfp branch, so the issue is moot at this point.

**Comment by JamesWekel** [comment]
Fish,

I think the 4 files difference is a commit timing issue. [mcisho's](https://github.com/mcisho) commit [08f4ea1](https://github.com/SDL-Hercules-390/hyperion/commit/08f4ea12ce8204815ca291618c86bd827301f994) updated `ieee.c`, and `zvector.c`. BUT my pull request was based on the sharedvfr branch before that commit and only updated `opcode.c` and `zvector2.c`.

Could that be the issue? 

On Windows, I periodically use SourceGear DiffMerge for directory / file differences. As I'm doing most of my development using VS Code to a remote Linux system, for file differences, I use VS Code's  build-in file compare. Still, need to look for a directory compare tool.

Jim

**Comment by wrljet** [comment]
For Windows, WinMerge is good.

**Comment by Fish-Git** [comment]
I personally recommend **[ExamDiff Pro](https://www.prestosoft.com/edp_examdiffpro.asp)**. I've been using if for years and _love_ it! It's not free though. Costs money. But it's well worth it IMHO!

**Pull request merged**
