### PR TITLE
IMAPS struct for icount command

### PR DESCRIPTION
**Pull request by salva-rczero**
An attempt to use strucs within structs, to avoid hardcode in IMAP_FIRST & IMAP_SIZE.

### CODE REVIEW

**Review by Fish-Git — COMMENTED** [review]
Your changes look okay to me.

But I have to ask, WHY do you feel such a change should be made?

All it does is complicate things IMO.

Isn't doing:

    sysblk.imap01[(_inst)[1]]++; 

easier than doing:

    sysblk.imaps.imap01[(_inst)[1]]++;

??

It's shorter! (fewer character to type!)

The ONLY advantage that I can see is with the `memset` instruction to set it to zeros. Other than that, I don't see any advantage.

If you want to make this change, I will allow it. (I will approve your Pull Request).

But only if you honestly feel it should be made. (Me? I don't care one way or the other.)

Do you honestly feel this change should be made? Yes? No?

**Comment by wrljet** [comment]
Fish, you're up late tonight.  Me, too.  :)

**Comment by salva-rczero** [comment]
The key is to avoid to update IMAP_SIZE if you need a new one:
```
#define IMAP_SIZE \
            ( sizeof(sysblk.imap01) \
            + sizeof(sysblk.imapa4) \
            + sizeof(sysblk.imapa5) \
...

```
that I forget in my first addition of imape7, imape7T.

So, **IMAP_SIZE** must to be carefully, and manually, maintained. While **sizeof sysblk.imaps** is done automatically by the compiler.

I agree that it is not a very frequent change, but after many decades supporting a large installation, I learned that many errors are due to the data structures and not so much to the code.

**Review by Fish-Git — APPROVED** [review]
> The key is to avoid to update IMAP_SIZE if you need a new one:
> 
> ```
> #define IMAP_SIZE \
>             ( sizeof(sysblk.imap01) \
>             + sizeof(sysblk.imapa4) \
>             + sizeof(sysblk.imapa5) \
> ...
> ```
> 
> that I forget in my first addition of imape7, imape7T.
> 
> So, **IMAP_SIZE** must to be carefully, and manually, maintained. While **sizeof sysblk.imaps** is done automatically by the compiler.
> 
> I agree that it is not a very frequent change, but after many decades supporting a large installation, I learned that many errors are due to the data structures and not so much to the code.

Agreed. Good point! Pull Request approved. &nbsp;`:)`

**Comment by Fish-Git** [comment]
Merged!

**Pull request merged**
