### PR TITLE
Merge pull request #1 from SDL-Hercules-390/master

### PR DESCRIPTION
**Pull request by rgschmi**
pull

### CODE REVIEW

**Comment by Fish-Git** [comment]
I'm not sure what you're trying to do, Bob, but this PR (Pull Request) doesn't contain any changes!&nbsp;`:(`

Pull Request rejected.

**Comment by rgschmi** [comment]
I'm still learning how to git from Windows.  I finally did a good pull, but I'm not sure I can repeat it.  I wanted to pick up your multiple IP address support or OSA so I'm ready for CTCI-WIN.   I checked line 616 of qeth.c and saw your comments on my pull.

**Comment by Fish-Git** [comment]
@rgschmi Bob,

FYI: You create Pull Requests to request to the Hercules team to pull changes from _your_ repository into the Hercules repository, not the other way around.  That is to say, if you've created a fix to a problem and the fix exists in _your_ repository and you want the Hercules team to merge your fix into _our_ repository, you would then create a Pull Request. The Hercules team would then "pull" your changes into our repository.

What you are wanting to do is a simple "git clone" of the current Hercules repository.  That is to say, what you are wanting to do is to create a local copy on your system of the current Hercules repository.  This will cause the data to flow in the other direction: git will create a copy of (essentially a download of) the Hercules repository from GitHub onto your local system.

Hope that helps!

**Comment by Fish-Git** [comment]
> ... I finally did a good pull, ...

Ah. Okay. If you already have a git clone of Hercules on your local system that you perhaps created at some point in the past, and simply want to "pick up" the latest set of changes, then yes, you would simply navigate to the directory containing that old out-of-date clone, and do a "git pull". That will download from GitHub all of the commits (changes) that we made since you did your original clone and merge them into your local copy, thereby updating (refreshing) your local copy so that it should then match 100% with what's on GitHub.

The usual procedure is:

    git clone      (to create your own private copy of Hercules's repository)
    (...time passes...)
    git pull      (to pickup new changes made since you did your clone)
    (...time passes...)
    git pull      (to pickup new changes made since you did your previous pull)
    ... etc...

Or, you can simply do what I sometimes do on occassion, and that is to simply _delete_ my local clone and then do the "git clone" again. Doing a "git clone" will _always__ get you the latest and greatest version of the repository.

Hope that helps too!

**Comment by rgschmi** [comment]
Duh!  Of course the pull request on the git page would be from the point of view of git, not me the user.  Now I git it!

Glad the pull failed!

Thanks for the tips.  I usually delete and do a git clone on linux  Sounds like that is what I need to do on Windows as well.

Thanks,

Bob

**Comment by Fish-Git** [comment]
> Now I git it!

`:))`

**Comment by ivan-w** [comment]
You guys are having too much git !
(Never mind - I'm tired and in the middle of something)

Carry on !

**Pull request closed without merging**
